#=========================================================================
# run_test.yml
#=========================================================================

name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sim:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        test_cmd:
          - ../tut3_verilog
          - ../lab1_imul
          - ../lab2_proc
          - ../lab3_mem
          - ../lab4_sys

    steps:
      - uses: actions/checkout@v4

      - name: Install verilator
        run: |
          wget --progress=dot:giga https://github.com/pymtl/verilator-ci-cache/raw/master/verilator-github-actions-5.026.tar.gz
          echo $PWD
          whoami
          tar -C ${HOME} -xzf verilator-github-actions-5.026.tar.gz
          echo "${HOME}/verilator/bin" >> $GITHUB_PATH
          echo "PKG_CONFIG_PATH=${HOME}/verilator/share/pkgconfig:${PKG_CONFIG_PATH}" >> $GITHUB_ENV

      - name: Check verilator
        run: |
          which verilator
          verilator --version
          pkg-config --modversion verilator
          pkg-config --cflags verilator

      - name: Install dependencies
        run: |
          sudo apt-get install -y graphviz
          pip install --upgrade pip
          pip install git+https://github.com/cornell-brg/pymtl3@pymtl4.0-dev

      - name: Run sim tests
        timeout-minutes: 10
        run: |
          cd src
          verilator -Wall --lint-only PairTripleDetector.v
#          iverilog -Wall -g2012 -o PairTripleDetector_test PairTripleDetector_test.v
#          ./PairTripleDetector_test
